#!/bin/sh

emitstatus()
{
	STATFD=$1
	shift

	( eval $* )
	echo $? 1>&${STATFD}
}

foo()
{
	echo "In foo()" 1>&2
	ls ${1+"$@"}
}

bar()
{
	echo "In bar()" 1>&2
	sed 's/^/[bar] /'
	
}

baz()
{
	echo "In baz()" 1>&2
	while read LINE ; do
		echo "[baz] $LINE"
	done
	
}

do_normal_pipe()
{
	foo ${1+"$@"} | bar | baz
}

do_special_pipe()
{
	exec 3>&1
	STATUSLIST=` { emitstatus 4 foo ${1+"$@"} \
			| emitstatus 4 bar \
			| emitstatus 4 baz \
			1>&3 ; } 4>&1 `
	exec 3>&- 4>&-

	echo "do_special_pipe(): STATUSLIST <<${STATUSLIST}>>"

	case ${STATUSLIST} in
	*[1-9]*)	exit 1 ;;
	*)		exit 0 ;;
	esac
}

#do_normal_pipe
do_special_pipe
