#!/bin/sh

emitstatus()
{
	STATFD=$1
	shift

	( eval $* )
	echo $? 1>&${STATFD}
}

generate_sequence()
{
	n=1
	while [ "$n" != '11' ] ; do
		echo $n
		n=`expr $n + 1`
	done
}

process_sequence()
{
	while read LINE ; do
		set -- $LINE
		case ${1} in
		?)	echo "...0${LINE}" ;;
		*)	echo "Unexpected input: LINE ${LINE}" 1>&2 ; exit 1 ;;
		esac
	done
}

emit_result()
{
	while read LINE ; do
		sleep 1 && echo ":) GOT ${LINE}"
	done
}

###	argument handling
#
#PATTERN=$1
#if [ -z "${PATTERN}" ] ; then
#	echo "$0: Missing PATTERN[, FILEs]" 1>&2
#	exit 1
#else
#	shift
#fi
#
#if [ -z "$1" ] ; then
#	echo "$0: Missing FILE[s]" 1>&2
#	exit 1
#fi

##	process

exec 3>&1
STATUSLIST=` { emitstatus 4 generate_sequence $@ \
		| emitstatus 4 process_sequence \
		| emitstatus 4 emit_result \
		1>&3 ; } 4>&1 `
exec 3>&- 4>&-

case ${STATUSLIST} in
*[1-9]*)	echo "EXIT BAD <<${STATUSLIST}>>" 1>&2 ; exit 1 ;;
*)		echo "EXIT OK" 1>&2 ; exit 0 ;;
esac
