#!/bin/sh

emitstatus()
{
	STATFD=$1
	shift

	( eval $* )
	echo $? 1>&${STATFD}
}

handle_find_pattern()
{
	PATTERN=$1
	shift

	FOUND=n
	while [ "$1" ] ; do
		FILE=$1
		shift

		grep ${PATTERN} ${FILE} && FOUND=y
	done

	if [ ${FOUND} = 'n' ] ; then
		echo "$0: handle_find_pattern(): PATTERN ${PATTERN} not found" 1>&2
		exit 1
	else
		exit 0
	fi
}

handle_found_pattern()
{
	while read LINE ; do
		echo ":) ${LINE}"
	done
}

##	argument handling

PATTERN=$1
if [ -z "${PATTERN}" ] ; then
	echo "$0: Missing PATTERN[, FILEs]" 1>&2
	exit 1
else
	shift
fi

if [ -z "$1" ] ; then
	echo "$0: Missing FILE[s]" 1>&2
	exit 1
fi

##	process

exec 3>&1
STATUSLIST=` { emitstatus 4 handle_find_pattern ${PATTERN} $@ \
		| emitstatus 4 handle_found_pattern 1>&3 ; } 4>&1 `
exec 3>&- 4>&-

case ${STATUSLIST} in
*[1-9]*)	exit 1 ;;
*)		exit 0 ;;
esac
