#!/bin/sh
##	build		STUBS (c) and GPLv2 Wm. Towle 1999-2010
##	Last modified	2010-12-28
##	Purpose		build control
#
#*   Open Source software - copyright and GPLv2 apply. Briefly:       *
#*    - No warranty/guarantee of fitness, use is at own risk          *
#*    - No restrictions on strictly-private use/copying/modification  *
#*    - No re-licensing this work under more restrictive terms        *
#*    - Redistributing? Include/offer to deliver original source      *
#*   Philosophy/full details at http://www.gnu.org/copyleft/gpl.html  *

TOPLEV=${PWD}
BINDIR=`dirname $0`
LIBDIR=${BINDIR}/lib

. ${LIBDIR}/project.sh
. ${LIBDIR}/stage.sh
. ${LIBDIR}/package.sh

emitstatus()
{
	STATFD=$1
	shift

	( eval ${1+"$@"} )
	eval "echo $? 1>&${STATFD}"
}

do_identify_packages()
{
# TODO: accept 'stage <n>' and 'all'
# FUTURE: accept names of specific package-script-dirs?
	stageconf_query_packages ${1+"$@"}
}

do_identify_scriptdirs()
{
	while read LINE ; do
		pkgconf_transform_stageconf buildspec ${LINE}
	done
}

do_process_scripts()
{
	while read LINE ; do
		pkgconf_build_package ${LINE}
	done
}

##	process

exec 3>&1
OFD=3
SFD=4
eval "STATUSLIST=\` { emitstatus ${SFD} do_identify_packages $@ \
		| emitstatus ${SFD} do_identify_scriptdirs \
		| emitstatus ${SFD} do_process_scripts 1>&${OFD} ; } ${SFD}>&1 \`"
exec 3>&- 4>&-

case ${STATUSLIST} in
*[1-9]*)	echo "$0: Failed; captured exit codes were:" ${STATUSLIST} 1>&2
		exit 1 ;;
*)		echo "$0: OK"
		exit 0 ;;
esac
